### ISSUE TITLE
Not working with Ip : Port on different machines.

### ISSUE THREAD

**Issue by ramisn** [adrianveracom/tlp2k13-whatsapp#1]
I cloned your Node.js app tlp2k13-whatsapp. It is working on my PC with different browsers.
But when I'm trying to run with different PC like,

Server is running on my PC, then I'm trying to access on another PC with my Ip : Port (3001), its showing cannot GET /index.html.
I tried some ways to route it, but I'm not able to do it.

Please help me regarding this.

**Comment by adrianveracom** [comment]
In the next couple days I'll upload an update with a more detailed example so you don't have this problem.

**Comment by ramisn** [comment]
Thank you..
Looking forward your updates..

**Comment by adrianveracom** [comment]
Hey, Sorry for the delay. Completely missed the email.

To use the client in this example you can just open the index.html file in your browser and will show the "chat".

This was an example that I made a few years ago, it could be improved a lot, so feel free to submit a PR if you want to give it some love!
